services:
  app:
    container_name: commander-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PORT=3000
      - USER_AGENT=${USER_AGENT}
      - TOPDECKGG_API_KEY=${TOPDECKGG_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}