FROM node:latest

WORKDIR /usr/src/api

# Copiar apenas os arquivos necessários para instalar as dependências
COPY package*.json ./

RUN npm install --quiet --no-optional --no-fund --loglevel=error

COPY . .

COPY ./.env.prod ./.env

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]