service: commander-api
frameworkVersion: "4.9.0"

custom:
  # webpack:
  #     webpackConfig: './webpack.config.js'
  #     includeModules: true
  serverless-layers:
    dependenciesPath: ./package.json
    compatibleRuntimes:
      - nodejs18.x
  params:
    stage: ${opt:stage, 'dev'}
    dbName: ${ssm:/${opt:stage, 'dev'}/backend/db/name}
    dbHost: ${ssm:/${opt:stage, 'dev'}/backend/db/host}
    dbPassword: ${ssm:/${opt:stage, 'dev'}/backend/db/password}
    dbPort: ${ssm:/${opt:stage, 'dev'}/backend/db/port}
    jwt_private_key: ${ssm:/${opt:stage, 'dev'}/backend/secret/jwt_private_key}
    jwt_public_key: ${ssm:/${opt:stage, 'dev'}/backend/secret/jwt_public_key}
    user_agent: ${ssm:/${opt:stage, 'dev'}/backend/secret/user_agent}
    deploymentBucket: ${ssm:/${opt:stage, 'dev'}/buckets/cmd-deployment-bucket}

plugins:
  - serverless-kms-alias
  - serverless-layers

package:
  excludeDevDependencies: true
  patterns:
    - "!tests/**"
    - "!node_modules/.bin/**" # Exclui bin치rios desnecess치rios
    - "!dockerfile.yml"
    - "!.env"
    - "!.env.exemple"
    - "node_modules/**" # Inclui todos os m칩dulos
    - "build/**" # Inclui o diret칩rio de build

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  tracing:
    lambda: true
  deploymentBucket:
    name: ${self:custom.params.deploymentBucket}
  profile: cmd_dev
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    IS_CLOUD: true
    CLOUD_AWS_REGION: ${self:provider.region}
    DB_NAME: ${self:custom.params.dbName}
    DB_HOST: ${self:custom.params.dbHost}
    DB_PASS: ${self:custom.params.dbPassword}
    DB_PORT: ${self:custom.params.dbPort}
    JWT_PRIVATE_KEY: ${self:custom.params.jwt_private_key}
    JWT_PUBLIC_KEY: ${self:custom.params.jwt_public_key}
    USER_AGENT: ${self:custom.params.user_agent}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  app:
    handler: build/src/lambda.handler
    description: "Commander API"
